### ISSUE TITLE
format parameter should be optional

### ISSUE THREAD

**Issue by rdmueller** [springfox/springfox-grails-integration#11]
the current version displays the format parameter as "required" but it should be optional.
I even wouldn't have expected it to show up since swagger handles the format through headers.

http://localhost:8080/swagger-ui.html#!/genre/indexGenreUsingGET

**Comment by dilipkrish** [comment]
I agree. The first pass was to get it working with the right urls :)

**Comment by dilipkrish** [comment]
It works now as we'd expect let me know if you see issues.

**Comment by dilipkrish** [comment]
Also it can be eliminated via fixing the url mappings, which is a work around.
