### ISSUE TITLE
OPTIONS /edit?

### ISSUE THREAD

**Issue by rdmueller** [springfox/springfox-grails-integration#12]
What are the OPTIONS endpoints for? I tried to invoke `http://localhost:8080/genre/edit` through postman and got a 404 back...

**Comment by dilipkrish** [comment]
The `OPTIONS` endpoints are a safe way to expose endpoints that don't have UrlMappings. The idea being they are not destructive and they can be filtered via the springfox docket.

**Comment by rdmueller** [comment]
hm. those endpoints seem not to exist...
maybe they should be filtered by default...

**Comment by dilipkrish** [comment]
Thats what I was thinking... but I wasn't sure that will always be the case.
