### ISSUE TITLE
Dependencies conflicts between spring security and springfox?

### ISSUE THREAD

**Issue by sevenseconds** [springfox/springfox-grails-integration#17]
I got an error as below, this happens only when I install both spring-security-rest plugin and springfox-grails plugin. When I remove the spring security rest. Springfox is back to work again. Any idea?

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.scanners.CachingOperationReader]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 37 common frames omitted
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.maximumSize(CacheBuilder.java:407)
	at springfox.documentation.spring.web.scanners.CachingOperationReader.<init>(CachingOperationReader.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 39 common frames omitted

**Comment by dilipkrish** [comment]
I think your perhaps pulling in a different version of google guava than we expect. Could you confirm the version in your classpath?

**Comment by sevenseconds** [comment]
In the springfox-grails it requires version 18, but springfox-spring-web requires guava version 20. Thus the version on the classpath is 20.0

> +--- io.springfox.grails:springfox-grails:1.0.1-SNAPSHOT
|    +--- com.google.guava:guava:18.0 -> 20.0
|    +--- com.fasterxml:classmate:1.3.3
|    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|    +--- io.springfox:springfox-spi:2.7.0
|    |    \--- io.springfox:springfox-core:2.7.0
|    |         +--- net.bytebuddy:byte-buddy:1.6.14
|    |         +--- com.google.guava:guava:18.0 -> 20.0
|    |         +--- com.fasterxml:classmate:1.3.3
|    |         +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |         +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE
|    |         |    +--- org.springframework:spring-beans:4.0.9.RELEASE -> 4.3.9.RELEASE (*)
|    |         |    +--- org.springframework:spring-context:4.0.9.RELEASE -> 4.3.9.RELEASE (*)
|    |         |    +--- org.springframework:spring-aop:4.0.9.RELEASE -> 4.3.9.RELEASE (*)
|    |         |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
|    |         \--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE
|    |              +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |              \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
|    +--- io.springfox:springfox-core:2.7.0 (*)
|    +--- io.springfox:springfox-swagger2:2.7.0
|    |    +--- io.swagger:swagger-annotations:1.5.13
|    |    +--- io.swagger:swagger-models:1.5.13
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.5 -> 2.8.8
|    |    |    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|    |    |    \--- io.swagger:swagger-annotations:1.5.13
|    |    +--- io.springfox:springfox-spi:2.7.0 (*)
|    |    +--- io.springfox:springfox-schema:2.7.0
|    |    |    +--- io.springfox:springfox-core:2.7.0 (*)
|    |    |    \--- io.springfox:springfox-spi:2.7.0 (*)
|    |    +--- io.springfox:springfox-swagger-common:2.7.0
|    |    |    +--- io.swagger:swagger-annotations:1.5.13
|    |    |    +--- io.swagger:swagger-models:1.5.13 (*)
|    |    |    +--- io.springfox:springfox-spi:2.7.0 (*)
|    |    |    +--- io.springfox:springfox-schema:2.7.0 (*)
|    |    |    +--- io.springfox:springfox-spring-web:2.7.0
|    |    |    |    +--- org.reflections:reflections:0.9.11
|    |    |    |    |    +--- com.google.guava:guava:20.0
|    |    |    |    |    \--- org.javassist:javassist:3.21.0-GA -> 3.20.0-GA
|    |    |    |    +--- com.google.guava:guava:18.0 -> 20.0
|    |    |    |    +--- com.fasterxml:classmate:1.3.3
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |    |    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    |    |    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    |    |    |    \--- io.springfox:springfox-spi:2.7.0 (*)
|    |    |    +--- com.google.guava:guava:18.0 -> 20.0
|    |    |    +--- com.fasterxml:classmate:1.3.3
|    |    |    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    |    \--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    |    +--- io.springfox:springfox-spring-web:2.7.0 (*)
|    |    +--- com.google.guava:guava:18.0 -> 20.0
|    |    +--- com.fasterxml:classmate:1.3.3
|    |    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    |    \--- org.mapstruct:mapstruct:1.1.0.Final
|    +--- net.bytebuddy:byte-buddy:1.6.10 -> 1.6.14
|    +--- io.swagger:swagger-annotations:1.5.12 -> 1.5.13

**Comment by dilipkrish** [comment]
Thanks for catching that. I'll fix it
