### ISSUE TITLE
Rest-Ressources need serverURL configured

### ISSUE THREAD

**Issue by rdmueller** [springfox/springfox-grails-integration#4]
if `grails.serverURL` isn't configured, application will throw an exception.

Can be simply configured in `application.yml`

    grails.serverURL: http://localhost:8080

**Comment by dilipkrish** [comment]
@rdmueller How come its not breaking the sample grails app. Am I inadvertently doing something to make it work?

**Comment by rdmueller** [comment]
I see. The sample app uses a different profile than I do (web). That seems to be the reason. Might be something for the documentation - others might run into the same problem...

**Comment by dilipkrish** [comment]
Not sure what that means @rdmueller 🙄 I'm a grails novice. Could you perhaps update the [Readme.adoc](https://github.com/springfox/springfox-grails-integration/blob/master/README.adoc)? Or perhaps if the sample that is being used for contract testing isn't the idiomatic sample would you mind creating a sample that shows what you mean? I'd be happy to include it in the springfox.

**Comment by albert-hejy** [comment]
I run into the same problem with the profile "rest-api", and I noticed that "grails.serverURL" is added to [demo project](https://github.com/springfox/springfox-grails-demo/blob/master/grails-app/conf/application.yml).

Here is my error log.
```
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2239)
	at springfox.documentation.grails.GrailsActionAttributes.actionUrl(GrailsActionAttributes.java:113)
	at springfox.documentation.grails.GrailsActionContext.lambda$path$0(GrailsActionContext.java:83)
	at java.util.Optional.map(Optional.java:215)
	at springfox.documentation.grails.GrailsActionContext.path(GrailsActionContext.java:83)
```

**Comment by dilipkrish** [comment]
@albert-hejy what version of grails are u using?
